### ISSUE TITLE
🧑‍💻💸 Review tests setup

### ISSUE THREAD

**Issue by M365Bass** [M365Bass/spfx-jack#42]
**Proposed**
- [ ] #54
- [ ] #55
- [x] Separate Unit tests from E2E tests like [using projects](https://daveiscoding.com/separate-nodejs-unit-integration-and-e2e-tests-using-jest-projects)
- [x] ~~Find a metric for E2E tests as coverage not very meaningful~~ Coverage ok for now
- [x] Figure out how to mock once inside one (ex: mock execSync inside gitInit)

**Low hanging fruit**
- [x] Look into E2E tests failing when run out of order (ex: npmVersion after prettier) 
- [x] Automate coverage report with every commit (to a pull request)
- [ ] #56
- [ ] #57

🧑‍💻💸 stands for `Technical Debt`

**Comment by M365Bass** [comment]
Closes #37
