### ISSUE TITLE
 🔼 Minor enhancements

### ISSUE THREAD

**Issue by M365Bass** [M365Bass/spfx-jack#49]
- [ ] #53
- [ ] #52
- [x] https://github.com/M365Bass/spfx-jack/commit/1e2086593df9e063e753d3f591093d002eae57d5 Switch short command names to single letter
- [x] https://github.com/M365Bass/spfx-jack/commit/8eeab8976cb41a2056bc5b73cd06a7e231bac885 Run jest coverage report on any commit (including directly to main) 
- [x] ~~Mock~~ **spyOn** execSync within commands (ex: gitInit.js)
- [x] Add `sort-package-json` & `prettier` as dependencies & avoid npx
