### ISSUE TITLE
🧑‍💻💸 Technical debt 13-11-23

### ISSUE THREAD

**Issue by M365Bass** [M365Bass/spfx-jack#65]
### 1. Figure out how to move to ESM
- [ ] Chalk stuck with v4 as v5 is ESM
- [ ] Jest has ESM as experimental for ages
- [ ] spfx-jack itself needs to be ported from CommonJS to ESM

### 2. How do we have 100% coverage when the below are not covered?

**2.1 Unit tests for rem. commands**
- [ ] npmVersion
- [ ] runPrettier
- [ ] sortPackage

**2.2 Unit tests for rem. utils**
- [ ] chalk
- [ ] gitCommit
- [ ] prettifyPath
